name: integration
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - release-*
jobs:
  reproducibility:
    if: ${{ !startsWith(github.head_ref, 'renovate/') && contains(github.event.pull_request.labels.*.name, 'integration/reproducibility') }}
    uses: ./.github/workflows/reproducibility.yaml
